CREATE TABLE [dbo].[Table]
(
	[id_cliente] INT NOT NULL PRIMARY KEY, 
    [nome] VARCHAR(30) NOT NULL, 
    [data] VARCHAR(9) NOT NULL, 
    [telefone fixo] VARCHAR(12) NOT NULL, 
    [telefone movel] VARCHAR(15) NOT NULL, 
    [estado civil] VARCHAR(15) NOT NULL, 
    [rg] VARCHAR(15) NOT NULL, 
    [cpf] VARCHAR(16) NOT NULL, 
    [email] VARCHAR(30) NOT NULL, 
    [rua ] VARCHAR(35) NOT NULL, 
    [numero] VARCHAR(6) NOT NULL, 
    [complemeto] VARCHAR(8) NOT NULL, 
    [cep] VARCHAR(10) NOT NULL, 
    [tipo_funcionario] VARCHAR(20) NOT NULL, 
    [nome_empresa] VARCHAR(40) NOT NULL, 
    [cnpj] VARCHAR(20) NOT NULL, 
    [n_pis] VARCHAR(20) NOT NULL, 
    [profissao] VARCHAR(25) NOT NULL, 
    [cargo] VARCHAR(20) NOT NULL, 
    [renda_familiar] VARCHAR(15) NOT NULL, 
    [interesse_imovel] VARCHAR(10) NOT NULL, 
    [anexo1] VARCHAR(10) NULL, 
    [anexo2] VARCHAR(10) NULL, 
    [anexo3] VARCHAR(10) NULL, 
    [anexo4] VARCHAR(10) NULL, 
    [anexo5] VARCHAR(10) NULL, 
    [anexo6] VARCHAR(10) NULL, 
    [anexo7] VARCHAR(10) NULL, 
    [anexo8] VARCHAR(10) NULL, 
    [anexo9] VARCHAR(10) NULL, 
    [anexo10] VARCHAR(10) NULL, 
    [anexo11] VARCHAR(10) NULL, 
    [anexo12] VARCHAR(10) NULL, 
    [anexo13] VARCHAR(10) NULL, 
    [anexo14] VARCHAR(10) NULL, 
    [anexo15] VARCHAR(10) NULL, 
    [anexo16] VARCHAR(10) NULL, 
    [anexo17] VARCHAR(10) NULL, 
    [anexo18] VARCHAR(10) NULL, 
    [anexo19] VARCHAR(10) NULL, 
    [anexo20] VARCHAR(10) NULL, 
    [anexo21] VARCHAR(10) NULL, 
    [anexo22] VARCHAR(10) NULL, 
    [anexo23] VARCHAR(10) NULL, 
    [anexo24] VARCHAR(10) NULL
)